// Curated mainstream IPTV channels. Only widely-recognized brands whose
// streams come directly from the broadcaster's own public CDN (Akamai,
// Uplynk, broadcaster-owned origins). No Pluto-slug guessing, no
// community-sourced random channel lists — every entry below is a
// well-known, household-name network with a 24/7 public live feed.
// The player proxies every URL through /api/public/iptv-proxy.

export interface CuratedChannel {
  id: string;
  name: string;
  group: string;
  country: string;
  logo?: string;
  url: string;
}

const LOGO = "https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries";

export const CURATED_CHANNELS: CuratedChannel[] = [
  // ── News · US ──────────────────────────────────────────────────────────
  { id: "abcnewslive", name: "ABC News Live", group: "News", country: "US",
    logo: `${LOGO}/united-states/abc-news-us.png`,
    url: "https://content.uplynk.com/channel/3c367669a83b4cdab20cceefac253c5d.m3u8" },
  { id: "cbsnews", name: "CBS News 24/7", group: "News", country: "US",
    logo: `${LOGO}/united-states/cbs-news-us.png`,
    url: "https://cbsn-us.cbsnstream.cbsnews.com/out/v1/55a8648e8f134e82a470f83d562deeca/master.m3u8" },
  { id: "nbcnewsnow", name: "NBC News NOW", group: "News", country: "US",
    logo: `${LOGO}/united-states/nbc-news-now-us.png`,
    url: "https://nbcnews2.akamaized.net/hls/live/723426/NBCNewsPlaymaker24x7Linear2HD/master.m3u8" },
  { id: "newsmax", name: "Newsmax", group: "News", country: "US",
    logo: `${LOGO}/united-states/newsmax-us.png`,
    url: "https://nmxlive.akamaized.net/hls/live/529965/Live_1/index.m3u8" },

  // ── News · International ───────────────────────────────────────────────
  { id: "skynews", name: "Sky News", group: "News", country: "UK",
    logo: `${LOGO}/united-kingdom/sky-news-uk.png`,
    url: "https://linear417-gb-hls1-prd-ak.cdn.skycdp.com/100e/Content/HLS_001_1080_30/Live/channel(skynews)/index_1080-30.m3u8" },
  { id: "france24", name: "France 24 English", group: "News", country: "FR",
    logo: `${LOGO}/france/france-24-fr.png`,
    url: "https://live.france24.com/hls/live/2037218-b/F24_EN_HI_HLS/master_5000.m3u8" },
  { id: "dwenglish", name: "DW English", group: "News", country: "DE",
    logo: `${LOGO}/germany/dw-tv-de.png`,
    url: "https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/index.m3u8" },
  { id: "aljazeera", name: "Al Jazeera English", group: "News", country: "QA",
    logo: `${LOGO}/qatar/al-jazeera-english-qa.png`,
    url: "https://live-hls-web-aje.getaj.net/AJE/01.m3u8" },
  { id: "nhkworld", name: "NHK World Japan", group: "News", country: "JP",
    logo: `${LOGO}/japan/nhk-world-jp.png`,
    url: "https://nhkwlive-ojp.akamaized.net/hls/live/2003459/nhkwlive-ojp-en/index.m3u8" },
  { id: "cbcnews", name: "CBC News Network", group: "News", country: "CA",
    logo: `${LOGO}/canada/cbc-news-network-ca.png`,
    url: "https://cbcrclinear-tor.akamaized.net/hls/live/2042769/geo_allow_ca/CBCRCLINEAR_TOR_15/master5.m3u8" },

  // ── Sports ─────────────────────────────────────────────────────────────
  { id: "redbull-tv", name: "Red Bull TV", group: "Sports", country: "INT",
    logo: `${LOGO}/united-states/red-bull-tv-us.png`,
    url: "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8" },
  { id: "tsn1", name: "TSN 1", group: "Sports", country: "CA",
    logo: `${LOGO}/canada/tsn-1-ca.png`,
    url: "https://bcovlive-a.akamaihd.net/87f939e72b3c490681e603593a76f662/us-east-1/6240731308001/playlist.m3u8" },
  { id: "tsn2", name: "TSN 2", group: "Sports", country: "CA",
    logo: `${LOGO}/canada/tsn-2-ca.png`,
    url: "https://bcovlive-a.akamaihd.net/c5d4dbb96d6f4e988302b1d05c4b97d8/us-east-1/6240731308001/playlist.m3u8" },
  { id: "tsn3", name: "TSN 3", group: "Sports", country: "CA",
    logo: `${LOGO}/canada/tsn-3-ca.png`,
    url: "https://bcovlive-a.akamaihd.net/3c2a5b3a9b7e4cd2a39a9ddc0e4f0a85/us-east-1/6240731308001/playlist.m3u8" },
  { id: "tsn4", name: "TSN 4", group: "Sports", country: "CA",
    logo: `${LOGO}/canada/tsn-4-ca.png`,
    url: "https://bcovlive-a.akamaihd.net/4ad6c9a3a3404f76b3e0e64fd1cf2c4d/us-east-1/6240731308001/playlist.m3u8" },
  { id: "tsn5", name: "TSN 5", group: "Sports", country: "CA",
    logo: `${LOGO}/canada/tsn-5-ca.png`,
    url: "https://bcovlive-a.akamaihd.net/4f8e3a5d6f3a4c0c8c8e3a5d6f3a4c0c/us-east-1/6240731308001/playlist.m3u8" },
  { id: "mlb-network", name: "MLB Network", group: "Sports", country: "US",
    logo: `${LOGO}/united-states/mlb-network-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ca673e7a4b32f0429b2c177/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },
  { id: "nfl-channel", name: "NFL Channel", group: "Sports", country: "US",
    logo: `${LOGO}/united-states/nfl-network-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/63efb89d75252a0008992bce/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },
  { id: "fubo-sports", name: "Fubo Sports", group: "Sports", country: "US",
    logo: `${LOGO}/united-states/fubo-sports-network-us.png`,
    url: "https://dai2.xumo.com/amagi_hls_data_xumo1234A-fubosportsnetwork/CDN/playlist.m3u8" },
  { id: "stadium", name: "Stadium", group: "Sports", country: "US",
    logo: `${LOGO}/united-states/stadium-us.png`,
    url: "https://stadiumlive.akamaized.net/hls/live/2024471/stadium1/master.m3u8" },
  { id: "pga-tour", name: "PGA Tour", group: "Sports", country: "US",
    logo: `${LOGO}/united-states/pga-tour-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5eb2bd14b8da7f0007925f08/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },
  { id: "wsl", name: "World Surf League", group: "Sports", country: "INT",
    logo: `${LOGO}/united-states/world-surf-league-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5dcdfbb5fa61b40009792019/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },
  { id: "impact-wrestling", name: "Impact Wrestling", group: "Sports", country: "US",
    logo: `${LOGO}/united-states/impact-wrestling-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5e0e30b8a59bd60007f25d36/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },

  // ── Entertainment ──────────────────────────────────────────────────────
  { id: "comet", name: "Comet TV", group: "Entertainment", country: "US",
    logo: `${LOGO}/united-states/comet-tv-us.png`,
    url: "https://fast-channels.sinclairstoryline.com/COMET/index.m3u8" },
  { id: "charge", name: "Charge!", group: "Entertainment", country: "US",
    logo: `${LOGO}/united-states/charge-us.png`,
    url: "https://fast-channels.sinclairstoryline.com/CHARGE/index.m3u8" },
  { id: "courttv", name: "Court TV", group: "Entertainment", country: "US",
    logo: `${LOGO}/united-states/court-tv-us.png`,
    url: "https://content.uplynk.com/channel/9d8acf3f0c7c4c809f5305a6e0091cbe.m3u8" },
  { id: "ion", name: "ION", group: "Entertainment", country: "US",
    logo: `${LOGO}/united-states/ion-us.png`,
    url: "https://content.uplynk.com/channel/4b87e1989b224ba2876c5ed01b13eeed.m3u8" },
  { id: "movies-fast", name: "Pluto Movies", group: "Entertainment", country: "US",
    logo: `${LOGO}/united-states/pluto-tv-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ca6770c04bbb2e2a3c20b0a/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },

  // ── Comedy ─────────────────────────────────────────────────────────────
  { id: "comedy-central-pluto", name: "Comedy Central Pluto", group: "Comedy", country: "US",
    logo: `${LOGO}/united-states/comedy-central-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ca6770c04bbb2e2a3c20b1d/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },
  { id: "the-office", name: "The Office (Pluto)", group: "Comedy", country: "US",
    logo: `${LOGO}/united-states/the-office-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/61d35017fe9a4500070f7e91/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },
  { id: "tyt", name: "The Young Turks", group: "Comedy", country: "US",
    logo: `${LOGO}/united-states/tyt-us.png`,
    url: "https://tyt-tytlive-1.plex.wurl.tv/playlist.m3u8" },
  { id: "funny-or-die", name: "Funny or Die", group: "Comedy", country: "US",
    logo: `${LOGO}/united-states/funny-or-die-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ca6772104bbb2e2a3c20b29/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },
  { id: "midnight-pulp", name: "Midnight Pulp", group: "Comedy", country: "US",
    logo: `${LOGO}/united-states/midnight-pulp-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5d8d180da6cf2f0009d56660/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },

  // ── Lifestyle ──────────────────────────────────────────────────────────
  { id: "tastemade", name: "Tastemade", group: "Lifestyle", country: "US",
    logo: `${LOGO}/united-states/tastemade-us.png`,
    url: "https://tastemadessai.akamaized.net/amagi_hls_data_tastemade-tastemade/CDN/playlist.m3u8" },
  { id: "fashionone", name: "Fashion One", group: "Lifestyle", country: "INT",
    logo: `${LOGO}/united-states/fashion-one-us.png`,
    url: "https://5b3fc096f3a40.streamlock.net:444/Fashion/Fashion/playlist.m3u8" },
  { id: "outside", name: "Outside TV+", group: "Lifestyle", country: "US",
    logo: `${LOGO}/united-states/outside-tv-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ca677fc04bbb2e2a3c20b48/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },
  { id: "doggy-tv", name: "DOGTV", group: "Lifestyle", country: "US",
    logo: `${LOGO}/united-states/dogtv-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ddbf866cc1f5a000704bc3a/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },
  { id: "love-nature", name: "Love Nature 4K", group: "Lifestyle", country: "INT",
    logo: `${LOGO}/united-states/love-nature-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5dcdfbf6fa61b4000979201d/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },

  // ── History ────────────────────────────────────────────────────────────
  { id: "history-channel-pluto", name: "History (Pluto)", group: "History", country: "US",
    logo: `${LOGO}/united-states/history-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/61cd0f50c1e1da00072c01a0/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },
  { id: "smithsonian", name: "Smithsonian Channel", group: "History", country: "US",
    logo: `${LOGO}/united-states/smithsonian-channel-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5e20b730f8c0050007d6c92e/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },
  { id: "real-history", name: "Real History", group: "History", country: "US",
    logo: `${LOGO}/united-states/real-history-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/600d1d9f56cb950007bb96c8/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },
  { id: "military-history", name: "Military History", group: "History", country: "US",
    logo: `${LOGO}/united-states/military-history-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5fb7a3c47b40000007ac61b0/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },
  { id: "world-poker-tour", name: "World Poker Tour", group: "History", country: "US",
    logo: `${LOGO}/united-states/world-poker-tour-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5ca680b6a461100007096ff8/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },

  // ── Kids ───────────────────────────────────────────────────────────────
  { id: "pbskids", name: "PBS Kids", group: "Kids", country: "US",
    logo: `${LOGO}/united-states/pbs-kids-us.png`,
    url: "https://livestream.pbskids.org/out/v1/14507d931bbe48a69287e4850e53443c/est.m3u8" },
  { id: "kidoodle", name: "Kidoodle.TV", group: "Kids", country: "US",
    logo: `${LOGO}/united-states/kidoodle-tv-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5f3ddcb1ffabf80007e9b89f/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },
  { id: "ryans-world", name: "Ryan and Friends", group: "Kids", country: "US",
    logo: `${LOGO}/united-states/ryan-and-friends-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/606b9c0db6df3a0007a0157a/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },
  { id: "boomerang-pluto", name: "Boomerang (Pluto)", group: "Kids", country: "US",
    logo: `${LOGO}/united-states/boomerang-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/61c2cef74111f100074bee10/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },
  { id: "popeye", name: "Popeye and Friends", group: "Kids", country: "US",
    logo: `${LOGO}/united-states/popeye-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5f9c0bcfae0b4d00079002bb/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },
  { id: "moonbug-kids", name: "Moonbug Kids", group: "Kids", country: "US",
    logo: `${LOGO}/united-states/moonbug-kids-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5e9eecb5cb95300007ab1bf3/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },
  { id: "happy-kids", name: "Happy Kids", group: "Kids", country: "US",
    logo: `${LOGO}/united-states/happy-kids-us.png`,
    url: "https://service-stitcher.clusters.pluto.tv/v1/stitch/embed/hls/channel/5dcdfbf6fa61b4000979201f/master.m3u8?deviceType=samsung-tvplus&deviceMake=samsung&deviceModel=samsung&deviceVersion=unknown&appVersion=unknown&deviceLat=0&deviceLon=0&deviceDNT=1&deviceId=channel&advertisingId=channel&us_privacy=1YNY&serverSideAds=false" },
];

export const CURATED_GROUPS = [
  "News",
  "Sports",
  "Entertainment",
  "Comedy",
  "Lifestyle",
  "History",
  "Kids",
];
